export { default as Page } from './Page';
export { default as Home } from './Home';
export { default as VocabularyDetail } from './VocabularyDetail';
export { default as NewVocabulary } from './NewVocabulary';
export { default as EditedVocabulary } from './EditedVocabulary';
export { default as About } from './About';
export { default as Login } from './Login';
export { default as Profile } from './Profile';
export { default as NotFoundPage } from './NotFoundPage';
